services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - memcached
    networks:
      - express-mysql
      - express-memcached
    ports:
      - '3005:3005'
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'barber'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - express-mysql
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
    networks:
      - express-memcached
networks:
  express-mysql:
  express-memcached:
volumes:
  my-db:
